#
# GitHub Actions workflow to check that
# pushed code builds on all supported platforms.
#
# Copyright (c) 2021 Greg Banks <gnb@fmeh.org>
#
name: build_on_push
on:
    push:
        branches: [ actions-experiment ]
jobs:
    build-and-test:
        name: Build And Test
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Prepare Linux Development Environment
              if: ${{ runner.os == 'Linux' }}
              run: sudo apt-get install autoconf automake make
            - name: Prepare MacOS Development Environment
              if: ${{ runner.os == 'macOS' }}
              run: echo nothing to see here
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Configure
              run: ./configure
            - name: Build
              run: make
            - name: Test
              run: make check
            - name: Upload Test Logs If Failed
              uses: actions/upload-artifact@v2
              if: failure()
              with:
                name: ${{ matrix.os }}-test-logs
                path: |
                    tests/test-suite.log
                    tests/t*.sh.log
