#
# GitHub Actions workflow to check that
# pushed code builds on all supported platforms.
#
# Copyright (c) 2021 Greg Banks <gnb@fmeh.org>
#
name: build_on_push
on:
    push:
        branches: [ actions-experiment ]
jobs:
    ubuntu-latest:
        name: ubuntu-latest
        runs-on: ubuntu-latest
        steps:
            - name: Prepare development environment
              run: sudo apt-get install autoconf automake make
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Configure
              run: ./configure
            - name: Build
              run: make
            - name: Test
              run: make check
            - uses: actions/upload-artifact@v2
              if: failure()
              with:
                name: test-logs
                path: |
                    tests/test-suite.log
                    tests/t*.sh.log
    macos-latest:
        name: macos-latest
        runs-on: macos-latest
        steps:
            - name: Prepare development environment
              run: echo nothing to see here
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Configure
              run: ./configure
            - name: Build
              run: make
            - name: Test
              run: make check
