#
# GitHub Actions workflow to check that
# pushed code builds on all supported platforms.
#
# Copyright (c) 2021 Greg Banks <gnb@fmeh.org>
#
name: Build and Test
on:
    push:
        branches: [ main ]
jobs:
    build-and-test:
        name: Build and Test
        strategy:
            matrix:
                container:
                    # Fedora 33 supported until approx 2021-11
                    - "fedora:33"
                    # Fedora 34 supported until approx 2022-05
                    - "fedora:34"
                    # Ubuntu 18.04, oldest LTS release still in Standard Support, until 2023-04
                    - "ubuntu:bionic"
                    # Ubuntu 20.04, latest LTS release, until 2025-04
                    - "ubuntu:focal"
                    # Ubuntu 20.10, interim release, supported until 2021-07
                    - "ubuntu:groovy"
                    # Ubuntu 21.04, interim release, supported until 2022-01
                    - "ubuntu:hirsute"
                os: [ubuntu-latest]
                include:
                    - os: macos-latest
        runs-on: ${{ matrix.os }}
        container: ${{ matrix.container }}
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Prepare development environment
              run: ci/prepare-dev-environment.sh
            - name: Configure
              run: ./configure
            - name: Build
              run: make
            - name: Test
              run: make check
            - name: Upload test logs if failed
              uses: actions/upload-artifact@v2
              if: failure()
              with:
                name: ${{ matrix.os }}-test-logs
                path: |
                    tests/test-suite.log
                    tests/t*.sh.log
