#
# GitHub Actions workflow to check that
# pushed code builds on all supported platforms.
#
# Copyright (c) 2021 Greg Banks <gnb@fmeh.org>
#
name: build_on_push
on:
    push:
        branches: [ actions-experiment ]
jobs:
    build-and-test:
        name: Build And Test
        strategy:
            matrix:
                container: ["fedora:33"]
                os: [ubuntu-latest]
                include:
                    - os: macos-latest
                    - os: ubuntu-latest
        runs-on: ${{ matrix.os }}
        container: ${{ matrix.container }}
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Prepare development environment
              run: ci/prepare-dev-environment.sh
            - name: Configure
              run: ./configure
            - name: Build
              run: make
            - name: Test
              run: make check
            - name: Upload test logs if failed
              uses: actions/upload-artifact@v2
              if: failure()
              with:
                name: ${{ matrix.os }}-test-logs
                path: |
                    tests/test-suite.log
                    tests/t*.sh.log
